<?php
/**
 *  This is an example of the WordPress API function 'add_shortcode'
 *  in action.  Some HTML and a <script> tag generated by an email
 *  marketing application (for example, MailChimp) are added into
 *  the function 'add_shortcode'.  Once the shortcode is registered to
 *  WordPress, add the shortcode tag (name) to the Popup content editor
 *  to run the script.
 *
 *  Use the code below this comment block when building your shortcode. When
 *  customized to your needs, add the registered shortcode to a plugin to run
 *  on your site.
 */
add_shortcode( 'mailprovider_form1', 'mailprovider_form1_shortcode' );
/**
 *  Register the shortcode to buffer and return the HTML and scripts to WordPress.
 *
 * @since 1.0.0
 *
 * @param string mailprovider_form1            The 'tag' (name) of the shortcode
 * @param string mailprovider_form1_shortcode  Register the shortcode with WordPress
 */
function mailprovider_form1_shortcode() {
	ob_start(); ?>

    <!--Insert your mail provider's HTML and JS form code here-->

	<?php
	return ob_get_clean();
}